### ISSUE TITLE
[Ask] sorry this is not a bug just a question

### ISSUE THREAD

**Issue by azkadev** [guchengxi1994/flutter_desktop#17]
Can Flutter be made 100% desktop?
I want to try making a Linux OS with Flutter as a full UI shell, but I can't display the default/native Linux app on top of the Flutter app.

can flutter do this?

sorry my english is bad, i use translate

**Comment by guchengxi1994** [comment]
@azkadev Here is a linux desktop based on flutter. https://github.com/dahliaOS, 
![image](https://github.com/guchengxi1994/flutter_desktop/assets/33513462/94718851-cf5a-4b92-ac1b-3f91ecdfdd08)

But I think it is much more difficult to implements a desktop like GNOME. If you want to display native linux app on flutter app, just create an icon and run it in another process when double click the icon.

**Comment by azkadev** [comment]
> @azkadev Here is a linux desktop based on flutter. https://github.com/dahliaOS, ![image](https://private-user-images.githubusercontent.com/33513462/305806664-94718851-cf5a-4b92-ac1b-3f91ecdfdd08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNTg5ODgsIm5iZiI6MTcwODM1ODY4OCwicGF0aCI6Ii8zMzUxMzQ2Mi8zMDU4MDY2NjQtOTQ3MTg4NTEtY2Y1YS00YjkyLWFjMWItM2Y5MWVjZGZkZDA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDE2MDQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkYjk5NjYxZTRmNmQ2NGYyY2RhOGE3MTJlODQ0OWQ2MDM3MjA3MTU0NjFhYTBiMDA0ZWUzZDhkMzFmNGM4MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LrMmSazIgH-NB7Ku7f_Kb5JutdNz3tH01V90M4zIwNs)
> 
> But I think it is much more difficult to implements a desktop like GNOME. If you want to display native linux app on flutter app, just create an icon and run it in another process when double click the icon.

oh ok, btw how do you compile your project?

I see there are local dependencies / packages

**Comment by guchengxi1994** [comment]
@azkadev change to `frb2` branch, and delete 
```yaml
flutter_hanoi:
    path: D:/github_repo/flutter_hanoi
```
in `dependency_overrides` .

If you have installed rust, you can compile this project directly.

Here is a release on windows. https://github.com/guchengxi1994/flutter_desktop/releases/tag/v0.1.10-frb2 , you can download Release.zip and try it.

If you ran into any problems when run this project, you can ask me about it.
